<a href="https://colab.research.google.com/github/Lathakh/2.Logistic-Regression-on-churn-modelling/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
1+1


2

In [2]:
import numpy as np

In [5]:
lst=[1,2,3,4]

# can we create array
arr=np.array(lst)

In [6]:
#list= collection of non homogenous  and it is slower
#array= homogenous and fast

type(arr)

numpy.ndarray

In [8]:
arr.shape # dimension of array

(4,)

In [12]:
arr1=np.array([[1,2,3],[4,5,6]])


In [13]:
arr1.shape

(2, 3)

In [14]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
tuple

In [17]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [18]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr1.dtype

dtype('int64')

In [21]:
#array from scratch

np.arange(1,10,2).shape

(5,)

In [23]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

In [22]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [24]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
,2

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<ipython-input-27-f157b314f30c>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  2("")


TypeError: ignored

In [26]:
np.arange(50,1)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [29]:
a=np.arange(50,1,2)

In [30]:
a

array([], dtype=int64)

In [31]:
np.linspace(1,20,40) # to create eqaully spaced element we use linearlyspace (40 is total number inbetween 1,20)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [32]:
np.linspace(1,20,40).shape

(40,)

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
#numpy give by default as floating values


np.ones((5,2,8)) #2,8 id inner array then 5

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [39]:
#math operation

np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
5+np.ones((3,5)) # broadcost operation

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [42]:
#identity  matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.eye(6).shape.reshape(12,3)

AttributeError: ignored

In [46]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
print("random number generation (uniform distrubution)")
np.random.rand(2,3)  # values ranging between 0-1

random number generation (uniform distrubution)


array([[0.60453512, 0.50000845, 0.1364145 ],
       [0.2065636 , 0.69747556, 0.34289677]])

In [49]:
print("random number following a normal distrubution with mean=0 and std=1")
print(np.random.randn(5,3))


random number following a normal distrubution with mean=0 and std=1
[[-0.43968317  0.13379221  0.50348256]
 [ 0.64478454 -0.46037462  0.59433149]
 [ 1.26199118 -1.7686433  -0.63959095]
 [ 0.30553333 -0.57330531 -0.95260149]
 [ 0.38960605 -0.84138148 -0.6405731 ]]


In [53]:
np.random.randint(1,100,10) # number would go change for each run

array([48, 64, 91, 89, 27, 86, 15, 37, 83,  4])

In [54]:
np.random.randint(1,100,10)

array([24, 22, 72, 50, 52,  6, 89, 61, 12, 12])

In [55]:
np.random.randint(1,100,(4,4))  # random numbers in array

array([[31, 46, 28, 11],
       [51, 11, 19, 27],
       [74, 17, 56, 38],
       [97, 36, 47, 93]])

In [58]:
arr=np.arange(0,11)

In [59]:
#slicing

arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [61]:
arr[-1]

10

In [62]:
arr[-1:7] # by default value is 1

array([], dtype=int64)

In [63]:
arr[-1:7:-1]

array([10,  9,  8])

In [65]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [66]:
arr[-1:5:-2]

array([10,  8,  6])

In [74]:
a=np.random.randint(2,100,20).reshape(5,4)
a

array([[84, 12, 69, 89],
       [83, 68, 71, 65],
       [57, 48, 78, 82],
       [13, 91, 58, 37],
       [18, 36, 68, 79]])

In [75]:
a[0:3,0:3]

array([[84, 12, 69],
       [83, 68, 71],
       [57, 48, 78]])

In [76]:
a[3:,1:]

array([[91, 58, 37],
       [36, 68, 79]])

In [82]:
a[2:4,1:3]

array([[48, 78],
       [91, 58]])

In [80]:
a[2:1,2:3]

array([], shape=(0, 1), dtype=int64)

In [83]:
## universal function


arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [84]:
arr1

array([[ 8,  9, 12],
       [ 9, 54, 18],
       [91, 30, 92]])

In [85]:
arr2

array([[36, 65, 88],
       [45, 95, 53],
       [41, 48, 57]])

In [86]:
arr1*arr2

array([[ 288,  585, 1056],
       [ 405, 5130,  954],
       [3731, 1440, 5244]])

In [87]:
arr1+arr2

array([[ 44,  74, 100],
       [ 54, 149,  71],
       [132,  78, 149]])

In [88]:
arr1/arr2

array([[0.22222222, 0.13846154, 0.13636364],
       [0.2       , 0.56842105, 0.33962264],
       [2.2195122 , 0.625     , 1.61403509]])

In [89]:
np.sqrt(arr1)

array([[2.82842712, 3.        , 3.46410162],
       [3.        , 7.34846923, 4.24264069],
       [9.53939201, 5.47722558, 9.59166305]])

In [90]:
np.exp(arr2)

array([[4.31123155e+15, 1.69488924e+28, 1.65163625e+38],
       [3.49342711e+19, 1.81123908e+41, 1.04137594e+23],
       [6.39843494e+17, 7.01673591e+20, 5.68572000e+24]])

In [91]:
np.log10(arr2)

array([[1.5563025 , 1.81291336, 1.94448267],
       [1.65321251, 1.97772361, 1.72427587],
       [1.61278386, 1.68124124, 1.75587486]])

In [93]:
arr1=np.arange(1,10)

In [94]:
arr1[2:]=1000

In [95]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])